
spring.application.name=donaciones-service
spring.threads.virtual.enabled=true

server.servlet.context-path=/api
server.port=${SERVER_PORT:8084}

servicio.notificaciones.url=${NOTIFICACIONES_URL:http://localhost:8083/notificaciones}
servicio.incentivos.url=${INCENTIVOS_URL:http://localhost:8082/perfiles}
servicio.logisticas.url=${LOGISTICAS_URL:http://localhost:8001/logistica}
