server.port=8084
spring.application.name=donaciones-service
spring.threads.virtual.enabled=true
server.servlet.context-path=/api
notificaciones.service.url=http://localhost:8081/notificaciones
servicio.incentivos.url=http://localhost:8082/perfiles
servicio.logisticas.url=http://localhost:8001/logistica
servicio.notificaciones.url=servicio.notificaciones.url=http://localhost:8083
