spring.application.name=incentivos-service
spring.threads.virtual.enabled=true
spring.main.allow-bean-definition-overriding=true

server.port=${SERVER_PORT:8082}

# URLs de servicios externos
servicio.donaciones.url=${DONACIONES_URL:http://localhost:8084}
servicio.notificaciones.url=${NOTIFICACIONES_URL:http://notificaciones-service:8083/}
servicio.n8n.url=${N8N_URL:http://localhost:8082/webhook/incentivos}

# --- Persistencia (MySQL) ---
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/incentivos_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:incentivos_user}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# --- Swagger / OpenAPI ---
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Ruta donde se expone la interfaz visual (Swagger UI)
springdoc.swagger-ui.path=/api-docs

# Ruta donde se genera el JSON de especificación OpenAPI
springdoc.api-docs.path=/v3/api-docs

# Ordenar los endpoints por métod0 HTTP y tags alfabéticamente
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha