spring.application.name=incentivos-service
spring.threads.virtual.enabled=true
spring.main.allow-bean-definition-overriding=true

server.port=${SERVER_PORT:8082}
servicio.donaciones.url=${DONACIONES_URL:http://localhost:8084}
servicio.notificaciones.url=${NOTIFICACIONES_URL:http://notificaciones-service:8083/notificaciones}
servicio.n8n.url=${N8N_URL:http://localhost:5678/webhook/incentivos}