spring.application.name=incentivos-service
spring.threads.virtual.enabled=true
spring.main.allow-bean-definition-overriding=true

server.servlet.context-path=/api

server.port=${SERVER_PORT:8084}
servicio.donaciones.url=${DONACIONES_URL:http://localhost:8085}
servicio.notificaciones.url=${NOTIFICACIONES_URL:http://notificaciones-service:8083/}
servicio.n8n.url=${N8N_URL:http://localhost:8082/webhook/incentivos}