spring.application.name=notificaciones-service
spring.threads.virtual.enabled=true

server.servlet.context-path=/api

server.port=${SERVER_PORT:8083}

servicio.n8n.url=${N8N_URL:http://localhost:5678/webhook/}