package ar.edu.utn.frba.ddsi.donaciones.models.entities.ServicioNotificaciones;

public enum TipoEventoNotificacion {
  DONACION_ASIGNADA_ENTIDAD_BENEFICIARIA,
  INACTIVIDAD_PERSONA_DONANTE,
  INICIO_RUTA_DONANTE,
  INICIO_RUTA_ENTIDAD_BENEFICIARIA
  INACTIVIDAD_PERSONA_DONANTE,
  DONACION_EN_VIAJE_ENTIDAD_BENEFICIARIA,
  COMPROBANTE_ENTREGA_ENTIDAD_BENEFICIARIA,
  DONACION_EN_VIAJE_PERSONA_DONANTE,
  COMPROBANTE_ENTREGA_PERSONA_DONANTE,
  ENTREGA_NO_RECIBIDA_PERSONA_DONANTE,
  ENTREGA_NO_RECIBIDA_ENTIDAD_BENEFICIARIA,
  ENTREGA_NO_RECIBIDA_ADMIN
}
