spring.application.name=logisticas-service
spring.threads.virtual.enabled=true

server.servlet.context-path=/api
server.port=${SERVER_PORT:8086}

# Base camiones
app.datasource.camiones.url=jdbc:mysql://localhost:3306/camiones
app.datasource.camiones.username=valentin
app.datasource.camiones.password=10032001

# Base choferes
app.datasource.choferes.url=jdbc:mysql://localhost:3306/choferes
app.datasource.choferes.username=valentin
app.datasource.choferes.password=10032001

# Base eventos
app.datasource.eventos.url=jdbc:mysql://localhost:3306/eventos
app.datasource.eventos.username=valentin
app.datasource.eventos.password=10032001

# Base items
app.datasource.items.url=jdbc:mysql://localhost:3306/items
app.datasource.items.username=valentin
app.datasource.items.password=10032001

# Base rutas
app.datasource.rutas.url=jdbc:mysql://localhost:3306/rutas
app.datasource.rutas.username=valentin
app.datasource.rutas.password=10032001

spring.jpa.hibernate.ddl-auto=update